-- CREACION:
CREATE TABLE DEPARTAMENTO (
  Codigo_D INT PRIMARY KEY,
  Nombre VARCHAR(255),
  Localizacion VARCHAR(255)
);

CREATE TABLE EMPLEADO (
  Id_E INT PRIMARY KEY,
  DNI_E VARCHAR(255),
  Nombre VARCHAR(255),
  Telefono VARCHAR(255),
  Salario FLOAT,
  Codigo_D INT REFERENCES DEPARTAMENTO(Codigo_D),
  Jefe_ID INT REFERENCES EMPLEADO(Id_E)
);


